### ISSUE TITLE
欢迎提问！！！

### ISSUE THREAD

**Issue by ZhiXiao-Lin** [ZhiXiao-Lin/nestify#67]
提问格式：
1、在什么需求下遇到什么问题。
2、框架现在为什么不能满足需求。
3、您期望的改动是什么样的。

**Comment by mfkickdx78** [comment]
火钳刘明

**Comment by PLAmao** [comment]
数据库的改动迁移，就是怎么使用typeorm的migration的配置

**Comment by Teeoo** [comment]
火钳刘明

**Comment by ZhiXiao-Lin** [comment]
> 1. 数据库的改动迁移
> 2. 没有看到使用typeorm的migration的配置
> 3. 期望结合package.json的run，使用typeorm的migration

你这个问题很有价值，新开一个 issue 吧！

**Comment by ZhiXiao-Lin** [comment]
> > 1. 数据库的改动迁移
> > 2. 没有看到使用typeorm的migration的配置
> > 3. 期望结合package.json的run，使用typeorm的migration
> 
> 你这个问题很有价值，新开一个 issue 吧！

https://github.com/ZhiXiao-Lin/nestify/issues/69#issue-455914279
