### ISSUE TITLE
启动时出现以下错误怎么解决

### ISSUE THREAD

**Issue by Darcy-shinet** [ZhiXiao-Lin/nestify#70]
(node:7471) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8086
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
(node:7471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which w

**Comment by ZhiXiao-Lin** [comment]
无法连接到 8086 端口，这个是 InfluxDB 的端口，要先安装相关软件
