### ISSUE TITLE
ExceptionsFilter 中的 request 和 response

### ISSUE THREAD

**Issue by tc9011** [ZhiXiao-Lin/nestify#71]
Hi，在我自己的项目中引（复）用（制）了你里面的 `ExceptionsFilter`，但是 `request.header` 中没有 `xhr` 属性，`response` 中没有 `code()` 和 `send()` 这些方法，我 nest 版本也是 6.0.0

**Comment by ZhiXiao-Lin** [comment]
这个项目底层 Http 库用的是 Fastify，不同的适配器API会有差别，您能提供您项目的相关信息吗？
request.header 中的 xhr 属性是我在前台自己附加的，如果您用的是 Express 库，那么可以直接使用 request.xhr。

**Comment by tc9011** [comment]
@ZhiXiao-Lin , 我好像知道错在哪里了，我没有用 Fastify ，可能有点差异，我再看看，谢谢
