### ISSUE TITLE
is this stack completed?

### ISSUE THREAD

**Issue by rmros** [ZhiXiao-Lin/nestify#72]
hi @ZhiXiao-Lin 
thank you for share your code
do you completed all features?
where is your roadmap

**Comment by ZhiXiao-Lin** [comment]
@rmros Thank you for your attention. Most of the features have been initially implemented, but there is a lack of unit testing and documentation, so it is expected that several refactorings will be needed.

**Comment by rmros** [comment]
@ZhiXiao-Lin  i login as sysadmin  then i went to user management and created new user there
i cant select any authority and  Permission preview

after i login with new user there is not any things

**Comment by rmros** [comment]
what is your opinion to create team management  feature

**Comment by ZhiXiao-Lin** [comment]
> @ ZhiXiao-Lin 我以sysadmin身份登录然后我去了用户管理并创建了新用户
> 我无法选择任何权限和权限预览
> 
> 我用新用户登录后没有任何东西



> @ZhiXiao-Lin i login as sysadmin then i went to user management and created new user there
> i cant select any authority and Permission preview
> 
> after i login with new user there is not any things

You need to set permissions for roles first.

**Comment by ZhiXiao-Lin** [comment]
> what is your opinion to create team management feature

Team management corresponds to organizational management, and you can set users as members of an organization.

**Comment by rmros** [comment]
@ZhiXiao-Lin  please see this video 
after created user:masoud i cant check any permission preview
https://drive.google.com/file/d/1Ffjhqvnk-47y9ThlSgKMUtwgFvTU8XqG/view?usp=sharing

**Comment by rmros** [comment]
> > what is your opinion to create team management feature
> 
> Team management corresponds to organizational management, and you can set users as members of an organization.

![Snag_962f9fc](https://user-images.githubusercontent.com/21344663/60355843-a321b800-99e4-11e9-9e57-9a16985435f0.png)

where exactly?

**Comment by ZhiXiao-Lin** [comment]
> @ZhiXiao-Lin please see this video
> after created user:masoud i cant check any permission preview
> https://drive.google.com/file/d/1Ffjhqvnk-47y9ThlSgKMUtwgFvTU8XqG/view?usp=sharing

[https://youtu.be/ndTOOX1Hq-4](url) I refactored this part of the code

**Comment by ZhiXiao-Lin** [comment]
> > > what is your opinion to create team management feature
> > 
> > 
> > Team management corresponds to organizational management, and you can set users as members of an organization.
> 
> ![Snag_962f9fc](https://user-images.githubusercontent.com/21344663/60355843-a321b800-99e4-11e9-9e57-9a16985435f0.png)
> 
> where exactly?

At present, I just create the relationship between users and organizations, and it is not difficult to realize the function of team management on this basis. Users can be filtered through the organization in user management.

**Comment by rmros** [comment]
> > @ZhiXiao-Lin please see this video
> > after created user:masoud i cant check any permission preview
> > https://drive.google.com/file/d/1Ffjhqvnk-47y9ThlSgKMUtwgFvTU8XqG/view?usp=sharing
> 
> https://youtu.be/ndTOOX1Hq-4 I refactored this part of the code,please pull up the latest code and build it.

thanks a lot, yess

**Comment by rmros** [comment]
after  pull up the latest code , i get error when login
请求超时!  meaning request time out

i tried with yarn db:init to recreate database but also got this message and i didn't login

![Snag_c6b3c75](https://user-images.githubusercontent.com/21344663/60380451-182fd480-9a5b-11e9-9af8-4d2d981df698.png)

**Comment by ZhiXiao-Lin** [comment]
> after pull up the latest code , i get error when login
> 请求超时! meaning request time out
> 
> i tried with yarn db:init to recreate database but also got this message and i didn't login
> 
> ![0FB69FA8-2DF8-4A1F-9898-66800075445F](https://user-images.githubusercontent.com/21344663/60380486-c471bb00-9a5b-11e9-90f5-5a73c321d4b4.GIF)

Is a new dependency Rabbitmq installed?

**Comment by rmros** [comment]
![Snag_d72e7ba](https://user-images.githubusercontent.com/21344663/60383209-53de9480-9a83-11e9-9a93-32c7d0bd8983.png)


yes , yarn installed all package.json files in all directory 


for you is working without any problem?

**Comment by ZhiXiao-Lin** [comment]
Please install RabbitMQ and try again. New functions related to it have been submitted together.

**Comment by ZhiXiao-Lin** [comment]
> ![Snag_d72e7ba](https://user-images.githubusercontent.com/21344663/60383209-53de9480-9a83-11e9-9a93-32c7d0bd8983.png)
> 
> yes , yarn installed all package.json files in all directory
> 
> for you is working without any problem?

Please install RabbitMQ and try again. New functions related to it have been submitted together.

**Comment by ZhiXiao-Lin** [comment]
> > ![Snag_d72e7ba](https://user-images.githubusercontent.com/21344663/60383209-53de9480-9a83-11e9-9a93-32c7d0bd8983.png)
> > yes , yarn installed all package.json files in all directory
> > for you is working without any problem?
> 
> Please install RabbitMQ and try again. New functions related to it have been submitted together.

Then clear all the browser's storage

**Comment by rmros** [comment]
@ZhiXiao-Lin  please add Rabbitmq config to you docker-compose.yml in server directory

**Comment by ZhiXiao-Lin** [comment]
> @ZhiXiao-Lin please add Rabbitmq config to you docker-compose.yml in server directory

ok

**Comment by rmros** [comment]
![Snag_e35a0c9](https://user-images.githubusercontent.com/21344663/60385682-083ae380-9aa1-11e9-86af-b1c35ff426f0.png)

it's working now,
why you switch to rabbitmq from elasticsearch and influxdb?

**Comment by ZhiXiao-Lin** [comment]
> ![Snag_e35a0c9](https://user-images.githubusercontent.com/21344663/60385682-083ae380-9aa1-11e9-86af-b1c35ff426f0.png)
> 
> it's working now,
> why you switch to rabbitmq from elasticsearch and influxdb?

Re-support after refactoring
