### ISSUE TITLE
graphql support

### ISSUE THREAD

**Issue by rmros** [ZhiXiao-Lin/nestify#74]
its nice to add graphql beside rest api
https://docs.nestjs.com/graphql/quick-start

**Comment by ZhiXiao-Lin** [comment]
> 很高兴在rest api https://docs.nestjs.com/graphql/quick-start旁边添加graphql
> [](https://docs.nestjs.com/graphql/quick-start)

Do they coexist? Can you provide PR to implement it in Fastify?

**Comment by rmros** [comment]
> > 很高兴在rest api [https://docs.nestjs.com/graphql/quick-start旁边添加graphql](https://docs.nestjs.com/graphql/quick-start%E6%97%81%E8%BE%B9%E6%B7%BB%E5%8A%A0graphql)
> 
> Do they coexist? Can you provide PR to implement it in Fastify?
Of course, they working independent ,,j
Not different you are using fastly or other

**Comment by ZhiXiao-Lin** [comment]
> > > 很高兴在rest api [https://docs.nestjs.com/graphql/quick-start旁边添加graphql](https://docs.nestjs.com/graphql/quick-start%E6%97%81%E8%BE%B9%E6%B7%BB%E5%8A%A0graphql)
> > 
> > 
> > Do they coexist? Can you provide PR to implement it in Fastify?
> > Of course, they working independent ,,j
> > Not different you are using fastly or other

Here's a GraphQL and Microservice framework based on Nest.js [https://github.com/notadd/notadd](https://github.com/notadd/notadd)

**Comment by rmros** [comment]
> > > > 很高兴在rest api [https://docs.nestjs.com/graphql/quick-start旁边添加graphql](https://docs.nestjs.com/graphql/quick-start%E6%97%81%E8%BE%B9%E6%B7%BB%E5%8A%A0graphql)
> > > 
> > > 
> > > Do they coexist? Can you provide PR to implement it in Fastify?
> > > Of course, they working independent ,,j
> > > Not different you are using fastly or other
> 
> Here's a GraphQL and Microservice framework based on Nest.js https://github.com/notadd/notadd


no need we upgrade monolithic to microservices just now,
but we can add graphql later if you think

**Comment by ZhiXiao-Lin** [comment]
> > > > > 很高兴在rest api [https://docs.nestjs.com/graphql/quick-start旁边添加graphql](https://docs.nestjs.com/graphql/quick-start%E6%97%81%E8%BE%B9%E6%B7%BB%E5%8A%A0graphql)
> > > > 
> > > > 
> > > > Do they coexist? Can you provide PR to implement it in Fastify?
> > > > Of course, they working independent ,,j
> > > > Not different you are using fastly or other
> > 
> > 
> > Here's a GraphQL and Microservice framework based on Nest.js https://github.com/notadd/notadd
> 
> no need we upgrade monolithic to microservices just now,
> but we can add graphql later if you think

I prefer Serverless

**Comment by ZhiXiao-Lin** [comment]
> > > > > > 很高兴在rest api [https://docs.nestjs.com/graphql/quick-start旁边添加graphql](https://docs.nestjs.com/graphql/quick-start%E6%97%81%E8%BE%B9%E6%B7%BB%E5%8A%A0graphql)
> > > > > 
> > > > > 
> > > > > Do they coexist? Can you provide PR to implement it in Fastify?
> > > > > Of course, they working independent ,,j
> > > > > Not different you are using fastly or other
> > > 
> > > 
> > > Here's a GraphQL and Microservice framework based on Nest.js https://github.com/notadd/notadd
> > 
> > 
> > no need we upgrade monolithic to microservices just now,
> > but we can add graphql later if you think
> 
> I prefer Serverless

GraphQL will be supported later, but its priority is not so high now.
