### ISSUE TITLE
casbin

### ISSUE THREAD

**Issue by rmros** [ZhiXiao-Lin/nestify#75]
notadd used casbin for RBAC and ....
https://github.com/notadd/nt-casbin

casbin is good solution for authorization system

what you think if you change nestify code to use this?

**Comment by ZhiXiao-Lin** [comment]
> notadd used casbin for RBAC and ....
> https://github.com/notadd/nt-casbin
> 
> casbin is good solution for authorization system
> 
> what you think if you change nestify code to use this?

I've evaluated all the popular permission validation packages of node before, but none of them satisfy me. I want to configure the permissions of roles dynamically when the program runs, not just once when it's initialized.

**Comment by hsluoyz** [comment]
Hi @ZhiXiao-Lin , Casbin has Management API and RBAC API to modify permissions or roles at run-time. It will satisfy your need. See details:

- Management API: https://casbin.org/docs/en/management-api
- RBAC API: https://casbin.org/docs/en/rbac-api

**Comment by ZhiXiao-Lin** [comment]
> Hi @ZhiXiao-Lin , Casbin has Management API and RBAC API to modify permissions or roles at run-time. It will satisfy your need. See details:
> 
> * Management API: https://casbin.org/docs/en/management-api
> * RBAC API: https://casbin.org/docs/en/rbac-api

Thank you. I'll study it carefully.
