### ISSUE TITLE
config property

### ISSUE THREAD

**Issue by rmros** [ZhiXiao-Lin/nestify#76]
hi @ZhiXiao-Lin 
thanks for new commits,
i cant find no_authority property in umijs router configuration,
where did you find it? :)

**Comment by ZhiXiao-Lin** [comment]
> hi @ZhiXiao-Lin
> thanks for new commits,
> i cant find no_authority property in umijs router configuration,
> where did you find it? :)

This is a custom property

**Comment by rmros** [comment]
> > hi @ZhiXiao-Lin
> > thanks for new commits,
> > i cant find no_authority property in umijs router configuration,
> > where did you find it? :)
> 
> This is a custom property

you just used in  authorized.js  
```
!route.no_authority &&
```
thanks
