### ISSUE TITLE
register page

### ISSUE THREAD

**Issue by rmros** [ZhiXiao-Lin/nestify#77]
register page is completed?
there is not any redux connect method for register react component
so there is not anu site-effect
so how sent register values to server?

UPDATED:

Ahh.. you use superFetch?

**Comment by ZhiXiao-Lin** [comment]
> register page is completed?
> there is not any redux connect method for register react component
> so there is not anu site-effect
> so how sent register values to server?

At present, the background management has no registration function and can only be assigned roles by super administrators.

**Comment by ZhiXiao-Lin** [comment]
> register page is completed?
> there is not any redux connect method for register react component
> so there is not anu site-effect
> so how sent register values to server?
> 
> UPDATED:
> 
> Ahh.. you use superFetch?

In the demo environment, the login will be registered at the same time.

**Comment by rmros** [comment]
> > register page is completed?
> > there is not any redux connect method for register react component
> > so there is not anu site-effect
> > so how sent register values to server?
> > UPDATED:
> > Ahh.. you use superFetch?
> 
> In the demo environment, the login will be registered at the same time.

im re-wrting all your codes to understand how they works,
so please keep open issues created by me, 
after finished i will close that
can i have your instant messenger id like telegram or whatsup?
send to this email
email: rm.rostami@gmail.com
thanks

**Comment by ZhiXiao-Lin** [comment]
> whatsup

Do you use Wechat?

**Comment by ZhiXiao-Lin** [comment]
> > > register page is completed?
> > > there is not any redux connect method for register react component
> > > so there is not anu site-effect
> > > so how sent register values to server?
> > > UPDATED:
> > > Ahh.. you use superFetch?
> > 
> > 
> > In the demo environment, the login will be registered at the same time.
> 
> im re-wrting all your codes to understand how they works,
> so please keep open issues created by me,
> after finished i will close that
> can i have your instant messenger id like telegram or whatsup?
> send to this email
> email: [rm.rostami@gmail.com](mailto:rm.rostami@gmail.com)
> thanks

Do you use Wechat?

**Comment by ZhiXiao-Lin** [comment]
> register page is completed?
> there is not any redux connect method for register react component
> so there is not anu site-effect
> so how sent register values to server?
> 
> UPDATED:
> 
> Ahh.. you use superFetch?

supFetch is not used and can be removed

**Comment by rmros** [comment]
> > > > register page is completed?
> > > > there is not any redux connect method for register react component
> > > > so there is not anu site-effect
> > > > so how sent register values to server?
> > > > UPDATED:
> > > > Ahh.. you use superFetch?
> > > 
> > > 
> > > In the demo environment, the login will be registered at the same time.
> > 
> > 
> > im re-wrting all your codes to understand how they works,
> > so please keep open issues created by me,
> > after finished i will close that
> > can i have your instant messenger id like telegram or whatsup?
> > send to this email
> > email: [rm.rostami@gmail.com](mailto:rm.rostami@gmail.com)
> > thanks
> 
> Do you use Wechat?

I saw your WeChat I'd at yours GitHub profile,
But WeChat is filter or banned,
So if you have another ways say to me
Thanks

**Comment by ZhiXiao-Lin** [comment]
> > > > > register page is completed?
> > > > > there is not any redux connect method for register react component
> > > > > so there is not anu site-effect
> > > > > so how sent register values to server?
> > > > > UPDATED:
> > > > > Ahh.. you use superFetch?
> > > > 
> > > > 
> > > > In the demo environment, the login will be registered at the same time.
> > > 
> > > 
> > > im re-wrting all your codes to understand how they works,
> > > so please keep open issues created by me,
> > > after finished i will close that
> > > can i have your instant messenger id like telegram or whatsup?
> > > send to this email
> > > email: [rm.rostami@gmail.com](mailto:rm.rostami@gmail.com)
> > > thanks
> > 
> > 
> > Do you use Wechat?
> 
> I saw your WeChat I'd at yours GitHub profile,
> But WeChat is filter or banned,
> So if you have another ways say to me
> Thanks

This is my telegram account number 18770221825.

**Comment by rmros** [comment]
thanks , i added ,
