### ISSUE TITLE
http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=MnLgQDf net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by websmallrabbit** [ZhiXiao-Lin/nestify#79]
http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=MnLgQDf net::ERR_CONNECTION_REFUSED
运行后，显示超市，控制台显示这个http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=MnLgQDf net::ERR_CONNECTION_REFUSED

**Comment by ZhiXiao-Lin** [comment]
关于超时的问题： 我没有配置 gzip 压缩，然后服务器带宽很低，首次加载需要很长时间。
关于 socket.io 报错的问题：应该是在配置文件中配置的生成环境的链接地址有错误，127.0.0.1:3000 需要改成服务器的地址

**Comment by ZhiXiao-Lin** [comment]
> 关于超时的问题： 我没有配置 gzip 压缩，然后服务器带宽很低，首次加载需要很长时间。
> 关于 socket.io 报错的问题：应该是在配置文件中配置的生成环境的链接地址有错误，127.0.0.1:3000 需要改成服务器的地址



> http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=MnLgQDf net::ERR_CONNECTION_REFUSED
> 运行后，显示超市，控制台显示这个http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=MnLgQDf net::ERR_CONNECTION_REFUSED

关于超时的问题： 我没有配置 gzip 压缩，然后服务器带宽很低，首次加载需要很长时间。
关于 socket.io 报错的问题：应该是在配置文件中配置的生成环境的链接地址有错误，127.0.0.1:3000 需要改成服务器的地址
